name: Caller Workflows

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false

  push:
    branches:
      - 'main'
      - 'releases/**'


jobs:
  call-ps-hash:
    uses: ./.github/workflows/called.yml
    with:
      PSScriptPath: ps/hash.ps1
      envvar: dev

  call-ps-output:
    uses: ./.github/workflows/called.yml
    with:
      PSScriptPath: ps/output.ps1
      envvar: dev