name: Encrypt

on:
  workflow_dispatch:
    inputs:
      EKMS:
        required: false
        default: false
        type: boolean
        description: Use Shell EKMS Keys ( Only for BUS )

      RotateKeys:
        required: false
        default: false
        type: boolean
        description: Use Azure Keyvault Self-Generated Keys

  push:
    branches:
      - 'main'
      - 'releases/**'

permissions:
  id-token: write
  contents: read

jobs:
  # job_1_plan:
  #   name: Running Job-1
  #   runs-on: ubuntu-latest
  #   environment: tfplan
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: PowerShell Script -
  #     run: |
  #       write-verbose "this is dummy" -verbose
  #     shell: pwsh


  job_2_rotate_keys:
    name: "Create or Rotate Keys"
    runs-on: ubuntu-latest
    #if: ${{ inputs.RotateKeys }}
    environment: tfplan
    steps:
      - uses: actions/checkout@v2

      - name: PowerShell Script - Import psfconfig
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          install-module psframework
          import-psfconfig -path ps/config-test.json | Register-PSFConfig -Scope FileUserShared
          #Register-psfconfig -module MyProject
          get-psfconfig
          Get-PSFConfigValue -FullName MyProject.Build.Repository
        shell: pwsh

      - name: PowerShell Script - test imported value
        run: |
          get-psfconfig
          Get-PSFConfigValue -FullName MyProject.Build.Artifactory | Write-Verbose -Verbose
          Get-PSFConfigValue -FullName MyProject.Build.Repository | Write-Verbose -Verbose
        shell: pwsh

  # job_3_encryption_keys:
  #   runs-on: ubuntu-latest
  #   name: EKMS Encryption Keys
  #   #if: ${{ inputs.EKMS }}
  #   needs: [job_2_rotate_keys]
  #   environment: tfplan
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: PowerShell Script
  #       run: |
  #         Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  #         install-module psframework
  #         Get-PSFConfigValue -FullName MyProject.Build.Artifactory
  #       shell: pwsh
