name: Import Replace TF

on:
  workflow_dispatch:
    inputs:
      Resources:
        required: true
        type: string
        description: Enter Resource Details
        default: "azurerm_resource_group.myrg2;/subscriptions/376f5cba-5717-4c24-af4c-bfa9fb5cd79e/resourceGroups/myrg2"
      ActivityType:
        required: true
        type: choice
        description: What would you like to do?
        options:
          - replace
          - import
        default: import
      azlogin:
        type: boolean
        description: Login to Azure
        required: true
        default: false

  push:
    branches:
      - 'main'
      - 'releases/**'


env:
  tf_actions_working_dir: infra

jobs:
  plan:
    name: Azure Resources Import Replace Job
    runs-on: ubuntu-latest
    environment: tfplan
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
    - uses: actions/checkout@v2


    - name: Load Environment variables
      uses: ./.github/actions/set-env-vars-ps-v2
      with:
        varFilePath: .github/variables/state.env::state

    - name: Log in to Azure using OIDC
      if: ${{ inputs.azlogin }}
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Generate the State File Name
      run: |
        Write-Host "${{inputs.Resources}}"

        $resources = "${{inputs.Resources}}"
        $resourceGroups = $resources.Split("::")

        terraform init -backend-config="resource_group_name=${{ env.backendAzureRmResourceGroupName}}" -backend-config="storage_account_name=${{ env.backendAzureRmStorageAccountName }}" -backend-config="container_name=${{ env.backendAzureRmContainerName }}" -backend-config="key=${{ env.stateFile }}"
        write-error "something wrong" -erroraction stop
      shell: pwsh
