name: Import Replace TF

on:
  workflow_dispatch:
    inputs:
      Resources:
        required: true
        description: Enter Resource Details
      ActivityType:
        required: true
        type: choice
        description: What would you like to do?
        options:
          - replace
          - import
        default: import


env:
  tf_actions_working_dir: infra

jobs:
  plan:
    name: Azure Resources Import Replace Job
    runs-on: ubuntu-latest
    environment: tfplan

    steps:
    - uses: actions/checkout@v2


    - name: Load Environment variables
      uses: ./.github/actions/set-env-vars-ps-v2
      with:
        varFilePath: .github/variables/state.env::state


      # - name: Generate the State File Name
      #   run: |
      #     Write-Host "${{inputs.Resources}}"
      #     Write-Host "${{ env.backendAzureRmResourceGroupName}}"
      #     Write-Host "${{ env.backendAzureRmStorageAccountName }}"
      #     Write-Host "${{ env.backendAzureRmContainerName }}"

      #     $resources = "${{inputs.Resources}}"
      #     $resourceGroups = $resources.Split("::")

      #     terraform init -backend-config="resource_group_name=${{ env.backendAzureRmResourceGroupName}}" -backend-config="storage_account_name=${{ env.backendAzureRmStorageAccountName }}" -backend-config="container_name=${{ env.backendAzureRmContainerName }}" -backend-config="key=${{ env.stateFile }}"
      #     write-error "something wrong" -erroraction stop
      #   shell: pwsh
