name: secrets

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  fetch-secret:
    name: fetch
    runs-on: ubuntu-latest
    environment: tfplan
    outputs:
      app_id: ${{ steps.create-secret.outputs.app_id_secret }}
      app-id2: ${{ steps.create-secret.outputs.app-id2 }}
    steps:
    - name: PowerShell Script - Create secrets
      id: create-secret
      run: |
        $app_id_mask=123
        echo "::add-mask::$app_id_mask"
        "app_id_secret=$app_id_mask" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "app-id2=456" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        echo ::set-output name=app_id::some
      shell: pwsh

    - name: PowerShell Script - output
      run: |
        ${{ steps.create-secret.outputs.app_id_secret }}
        ${{ steps.create-secret.outputs.app-id2 }}
      shell: pwsh
  use-secret:
    name: test secret
    runs-on: ubuntu-latest
    environment: tfplan
    needs: [fetch-secret]
    steps:
    - uses: actions/checkout@v2

    - name: PowerShell Script - Mask
      id: mask-secret
      run: |
        $app_id_mask= ${{ needs.fetch-secret.outputs.app-id2  }}
        echo "::add-mask::$app_id_mask"
        "secret2=$app_id_mask" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        echo ::set-output name=app_id::some
      shell: pwsh

    - name: PowerShell Script - test secret
      id: test-secret
      uses: ./.github/actions/test-secret
      with:
          secret1: ${{ needs.fetch-secret.outputs.app_id }}
          secret2: ${{ steps.mask-secret.outputs.secret2  }}
