name: DataTopologies

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  fetch-secret:
    name: fetch
    runs-on: ubuntu-latest
    environment: tfplan
    outputs:
      app_id: ${{ steps.create_secret.outputs.app_id }}
      app_id2: ${{ steps.create_secret.outputs.app_id2 }}


    steps:
    # - uses: actions/checkout@v2

    # - name: Load Environment variables
    #   uses: ./.github/actions/set-env-vars-ps-v2
    #   with:
    #     varFilePath: .github/variables/hash.env::one

    - name: PowerShell Script - Create secrets
      id: create-secret
      run: |
        "app_id=123" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "app_id2=456" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
      shell: pwsh

    # - name: PowerShell Script - adls loop
    #   run: |
    #     . ps/dthash.ps1
    #   shell: pwsh
  use-secret:
    name: test secret
    runs-on: ubuntu-latest
    environment: tfplan
    needs: [fetch-secret]
    steps:
    - uses: actions/checkout@v2

    - name: PowerShell Script - test secret
      id: test-secret
      uses: .github/actions/test-secret
      with:
        secret1: ${{ needs.fetch-secret.outputs.app_id }}
        secret2: ${{ needs.fetch-secret.outputs.app_id2  }}
