name: secrets

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  fetch-secret:
    name: fetch
    runs-on: ubuntu-latest
    environment: tfplan
    steps:
    - name: PowerShell Script - Load secrets
      id: load-secret
      run: |
        . ps/load-secret.ps1
      shell: pwsh

    - name: PowerShell Script - output
      run: |
        ${{ env.cert }}
      shell: pwsh
  # use-secret:
  #   name: test secret
  #   runs-on: ubuntu-latest
  #   environment: tfplan
  #   needs: [fetch-secret]
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: PowerShell Script - Mask
  #     id: mask-secret
  #     run: |
  #       $app_id_mask= ${{ needs.fetch-secret.outputs.app-id2  }}
  #       echo "::add-mask::$app_id_mask"
  #       "secret2=$app_id_mask" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
  #       echo ::set-output name=app_id::some
  #     shell: pwsh

  #   - name: PowerShell Script - test secret
  #     id: test-secret
  #     uses: ./.github/actions/test-secret
  #     with:
  #         secret1: ${{ needs.fetch-secret.outputs.app_id }}
  #         secret2: ${{ steps.mask-secret.outputs.secret2  }}
