name: DataTopologies

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  fetch-secret:
    name: fetch
    runs-on: ubuntu-latest
    environment: tfplan
    outputs:
      app_id: ${{ steps.create_secret.outputs.app_id }}
      appid2: ${{ steps.create_secret.outputs.appid2 }}
    steps:
    - name: PowerShell Script - Create secrets
      id: create-secret
      run: |
        #"app_id=123" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        echo "appid2=some" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        echo ::set-output name=app_id::some
      shell: pwsh

    - name: PowerShell Script - output
      run: |
        ${{ steps.create_secret.outputs.app_id }}
        ${{ steps.create_secret.outputs.appid2 }}
      shell: pwsh
  use-secret:
    name: test secret
    runs-on: ubuntu-latest
    environment: tfplan
    needs: [fetch-secret]
    steps:
    - uses: actions/checkout@v2

    - name: PowerShell Script - test secret
      id: test-secret
      uses: ./.github/actions/test-secret
      with:
          secret1: ${{ needs.fetch-secret.outputs.app_id }}
          secret2: ${{ needs.fetch-secret.outputs.appid2  }}
