name: Azure Deploy

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false


  pull_request:
    paths:
    - infra/**

  push:
    branches:
      - 'main'
      - 'releases/**'


env:
  tf_actions_working_dir: infra

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Azure Job
    runs-on: ubuntu-latest
    environment: tfplan

    steps:
    - uses: actions/checkout@v2

    # - name: Log in to Azure using client secret
    #   #if: ${{ inputs.azlogin }}
    #   uses: azure/login@v1
    #   with:
    #       creds: ${{secrets.AZURE_CREDENTIALS}}
    #       enable-AzPSSession: true

    # - name: Azure PowerShell InlineScript - run az ps commands
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       get-azresourcegroup
    #     azPSVersion: "latest"

    - name: PowerShell Script - test environment variables
      run: |
        $pwd
        dir $pwd | select name,fullname
        write-output ("{0} - {1} - {2}" -f  ("#" * 30),'github workspace',("#" * 30))
        dir ${{ github.workspace }} | select name,fullname
        . ps/myps.ps1
      shell: pwsh